# Generated by Django 4.2.7 on 2025-12-18 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='e.g., 2024')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-year', '-semester'],
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., MIT201', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Data Structures', max_length=200)),
                ('credit_units', models.IntegerField(default=3, help_text='Credit factor for the unit (typically 1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.academicyear')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (70-100%) - Excellent'), ('B', 'B (60-69%) - Good'), ('C', 'C (50-59%) - Satisfactory'), ('D', 'D (40-49%) - Pass'), ('E', 'E (0-39%) - Fail')], editable=False, help_text='Auto-calculated based on score', max_length=1)),
                ('points', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Weighted points (score × credit_units)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.unit')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='GPACalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, help_text='Weighted Mean Average (WMA)', max_digits=5)),
                ('total_points', models.DecimalField(decimal_places=2, help_text='Total weighted points', max_digits=8)),
                ('total_credit_units', models.IntegerField(help_text='Total credit units completed')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_calculations', to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_calculations', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'GPA Calculations',
                'ordering': ['-academic_year__year', '-academic_year__semester'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
