# Generated by Django 4.2.7 on 2026-01-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_notifications', models.CharField(choices=[('gpa_change', 'GPA Changes'), ('honor_threshold', 'Honor Level Threshold (within 2 points)'), ('low_grade', 'Grades Below Target'), ('all', 'All Notifications')], default='all', max_length=50)),
                ('email_on_alerts', models.BooleanField(default=True)),
                ('dashboard_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Average score across all units', max_digits=5)),
                ('best_performing_unit', models.CharField(blank=True, max_length=50)),
                ('worst_performing_unit', models.CharField(blank=True, max_length=50)),
                ('struggling_units', models.TextField(blank=True, help_text='JSON array of struggling units')),
                ('gpa_trend', models.CharField(blank=True, help_text="'improving', 'stable', 'declining'", max_length=20)),
                ('units_at_risk', models.IntegerField(default=0, help_text='Number of units with grades below C')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_analytics', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('gpa_increase', 'GPA Increased'), ('gpa_decrease', 'GPA Decreased'), ('honor_approaching', 'Approaching Honor Level'), ('low_grade', 'Low Grade Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_alerts', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
